spring.application.name=secure-resource-api
spring.datasource.url=jdbc:postgresql://localhost:5432/secure_resource_db
spring.datasource.username=secure_resource_app
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
